name: CI/CD main

on:
  push:
    branches:
      - main

jobs:
  docker-build:
    name: Build and push docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Docker login
        run: docker login ${{ secrets.REGISTRY_URL }} -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build docker image
        run: docker build --pull -t ${{ secrets.REGISTRY_IMAGE }} .

      - name: Push docker image
        run: docker push ${{ secrets.REGISTRY_IMAGE }}